# PyInstaller spec for Navecraft.
# Build:  pyinstaller Navecraft.spec
# Output: dist/Navecraft/Navecraft.exe (Windows) or dist/Navecraft/Navecraft (Linux/macOS)

# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'pygame',
        'numpy',
        'noise',
        'core.audio',
        'core.game',
        'core.input',
        'core.renderer',
        'systems.tutorial',
        'systems.codex',
        'systems.feedback',
        'systems.camera',
        'systems.background',
        'systems.lighting',
        'systems.galaxy',
        'systems.factions',
        'systems.skills',
        'systems.bosses',
        'systems.game_modes',
        'systems.achievements',
        'systems.stats',
        'systems.gamepad',
        'systems.rebind',
        'systems.spatial_hash',
        'systems.pool',
        'systems.profiler',
        'systems.day_night',
        'systems.weather',
        'systems.speedrun',
        'systems.replay',
        'systems.photo_mode',
        'systems.mod_loader',
        'systems.telemetry',
        'systems.planet_names',
        'systems.accessibility',
        'entities.merchant',
        'ui.minimap',
        'ui.compass',
        'ui.tooltip',
        'ui.inventory_screen',
        'ui.crafting_screen',
        'ui.map_screen',
        'ui.death_screen',
        'ui.help_overlay',
        'ui.codex_screen',
        'ui.settings_screen',
        'utils.display',
        'utils.config',
        'utils.i18n',
        'utils.font',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter', 'matplotlib', 'PIL'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Navecraft',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Navecraft',
)
