"""
In-game codex - lore entries, resource/enemy/biome descriptions, glossary.
"""

import json
import os
from utils.i18n import get_language


CODEX_DATA = {
    'resources': {
        'IRON': {
            'pt': ('Ferro', 'Material estrutural comum. Usado para construção e crafting de kits.'),
            'en': ('Iron', 'Common structural material. Used in construction and repair kits.'),
            'es': ('Hierro', 'Material estructural común. Usado en construcción y kits.'),
        },
        'GOLD': {
            'pt': ('Ouro', 'Metal precioso de alta condutividade. Necessário para upgrades avançados.'),
            'en': ('Gold', 'High-conductivity precious metal. Needed for advanced upgrades.'),
            'es': ('Oro', 'Metal precioso conductor. Necesario para mejoras avanzadas.'),
        },
        'CRYSTAL': {
            'pt': ('Cristal', 'Cristais energéticos raros. Coração dos sistemas de propulsão e escudo.'),
            'en': ('Crystal', 'Rare energy crystals. Core of propulsion and shield systems.'),
            'es': ('Cristal', 'Cristales energéticos raros. Núcleo de propulsión y escudo.'),
        },
        'FUEL': {
            'pt': ('Combustível', 'Compostos voláteis que alimentam os motores.'),
            'en': ('Fuel', 'Volatile compound powering the engines.'),
            'es': ('Combustible', 'Compuesto volátil que alimenta los motores.'),
        },
        'OXYGEN': {
            'pt': ('Oxigênio', 'Cristais de O2 condensado. Mantém você vivo.'),
            'en': ('Oxygen', 'Condensed O2 crystals. Keeps you alive.'),
            'es': ('Oxígeno', 'Cristales de O2 condensado. Te mantiene vivo.'),
        },
    },
    'enemies': {
        'DRONE': {
            'pt': ('Drone', 'Rápido e frágil. Carga suicida — mantenha distância.'),
            'en': ('Drone', 'Fast and fragile. Suicide rusher — keep distance.'),
            'es': ('Dron', 'Rápido y frágil. Cargador suicida — mantén distancia.'),
        },
        'ANDROID': {
            'pt': ('Andróide', 'Resistente e metódico. Boa armadura.'),
            'en': ('Android', 'Tough and methodical. Heavy armor.'),
            'es': ('Androide', 'Resistente y metódico. Armadura pesada.'),
        },
        'SNIPER': {
            'pt': ('Sniper', 'Atira de longe. Aproxime-se ou faça curvas.'),
            'en': ('Sniper', 'Long-range attacker. Close in or zig-zag.'),
            'es': ('Sniper', 'Ataca a distancia. Acércate o zigzaguea.'),
        },
        'ARACHNOID': {
            'pt': ('Aracnoide', 'Multi-pernas. Veloz em terreno irregular.'),
            'en': ('Arachnoid', 'Multi-legged. Fast on rough terrain.'),
            'es': ('Aracnoide', 'Multipata. Veloz en terreno irregular.'),
        },
        'BOSS_DREADNAUGHT': {
            'pt': ('Dreadnaught', 'Mini-boss blindado. Múltiplas fases de combate.'),
            'en': ('Dreadnaught', 'Armored mini-boss. Multiple combat phases.'),
            'es': ('Dreadnaught', 'Mini-boss blindado. Varias fases de combate.'),
        },
    },
    'biomes': {
        'ROCK': {
            'pt': ('Rochoso', 'Mundos áridos ricos em ferro e ouro.'),
            'en': ('Rocky', 'Arid worlds rich in iron and gold.'),
            'es': ('Rocoso', 'Mundos áridos ricos en hierro y oro.'),
        },
        'ICE': {
            'pt': ('Gelado', 'Reservas de oxigênio e cristais frios.'),
            'en': ('Icy', 'Reserves of oxygen and cold crystals.'),
            'es': ('Helado', 'Reservas de oxígeno y cristales fríos.'),
        },
        'GAS': {
            'pt': ('Gasoso', 'Gigantes gasosos — apenas atmosfera, sem mineração.'),
            'en': ('Gas', 'Gas giants — atmosphere only, no mining.'),
            'es': ('Gaseoso', 'Gigantes gaseosos — solo atmósfera.'),
        },
        'METAL': {
            'pt': ('Metálico', 'Crostas de metais pesados.'),
            'en': ('Metal', 'Heavy-metal crusts.'),
            'es': ('Metálico', 'Cortezas de metales pesados.'),
        },
        'CRYSTAL': {
            'pt': ('Cristalino', 'Mundos prismáticos repletos de cristais energéticos.'),
            'en': ('Crystal', 'Prismatic worlds full of energy crystals.'),
            'es': ('Cristalino', 'Mundos prismáticos llenos de cristales.'),
        },
        'LAVA': {
            'pt': ('Vulcânico', 'Vulcões ativos e combustível abundante.'),
            'en': ('Volcanic', 'Active volcanoes and abundant fuel.'),
            'es': ('Volcánico', 'Volcanes activos y combustible abundante.'),
        },
        'TOXIC': {
            'pt': ('Tóxico', 'Nuvens venenosas — perigoso aproximar-se.'),
            'en': ('Toxic', 'Poisonous clouds — dangerous to approach.'),
            'es': ('Tóxico', 'Nubes venenosas — peligroso acercarse.'),
        },
        'RADIOACTIVE': {
            'pt': ('Radioativo', 'Cristais radioativos. Recompensa alta, risco alto.'),
            'en': ('Radioactive', 'Radioactive crystals. High reward, high risk.'),
            'es': ('Radiactivo', 'Cristales radiactivos. Alta recompensa, alto riesgo.'),
        },
        'WATER': {
            'pt': ('Aquático', 'Oceanos profundos com oxigênio abundante.'),
            'en': ('Water', 'Deep oceans rich in oxygen.'),
            'es': ('Acuático', 'Océanos profundos ricos en oxígeno.'),
        },
        'DESERT': {
            'pt': ('Desértico', 'Dunas infinitas e tempestades de areia.'),
            'en': ('Desert', 'Endless dunes and sandstorms.'),
            'es': ('Desierto', 'Dunas infinitas y tormentas de arena.'),
        },
    },
    'glossary': {
        'HUD': {
            'pt': ('HUD', 'Heads-Up Display: barras de status sobrepostas no jogo.'),
            'en': ('HUD', 'Heads-Up Display: status bars overlaid on the game.'),
            'es': ('HUD', 'Visor de cabeza: barras de estado superpuestas.'),
        },
        'WARP': {
            'pt': ('Warp', 'Salto entre sistemas solares através de coordenadas estelares.'),
            'en': ('Warp', 'Jump between solar systems via stellar coordinates.'),
            'es': ('Warp', 'Salto entre sistemas vía coordenadas estelares.'),
        },
        'CULLING': {
            'pt': ('Culling', 'Otimização que descarta objetos fora da tela.'),
            'en': ('Culling', 'Optimization that discards off-screen objects.'),
            'es': ('Culling', 'Optimización que descarta objetos fuera de pantalla.'),
        },
    },
}

def _entry(idx, pt, en, es):
    return {'id': f'log_{idx:02d}', 'pt': f'Log #{idx:02d}: {pt}', 'en': f'Log #{idx:02d}: {en}',
            'es': f'Log #{idx:02d}: {es}'}


LORE_LOG_ENTRIES = [
    _entry(1, "O sinal de socorro veio de uma estação esquecida.",
              "The distress signal came from a forgotten station.",
              "La señal de auxilio vino de una estación olvidada."),
    _entry(2, "A radiação de Veridian-3 distorce qualquer comunicação.",
              "Veridian-3 radiation scrambles all communication.",
              "La radiación de Veridian-3 distorsiona toda comunicación."),
    _entry(3, "Encontrei destroços de uma frota desconhecida. Cristais cintilam.",
              "Found wreckage of an unknown fleet. Crystals shimmer.",
              "Encontré restos de una flota desconocida. Cristales brillan."),
    _entry(4, "Os piratas do Cinturão Norte cobram passagem em ouro.",
              "North-Belt pirates demand toll in gold.",
              "Los piratas del Cinturón Norte cobran peaje en oro."),
    _entry(5, "Federação patrulha as rotas próximas a Helios-Prime.",
              "The Federation patrols routes near Helios-Prime.",
              "La Federación patrulla las rutas cerca de Helios-Prime."),
    _entry(6, "Drone autônomo encontrado em um asteroide — sem identificação.",
              "Autonomous drone found on an asteroid — no ID.",
              "Drone autónomo en un asteroide — sin identificación."),
    _entry(7, "Cristais negros de Veridian têm valor lendário no mercado de Pyxis.",
              "Veridian black crystals fetch legendary prices on Pyxis market.",
              "Los cristales negros de Veridian valen una fortuna en Pyxis."),
    _entry(8, "Comerciantes Errantes cruzaram a anomalia gravitacional sem dano.",
              "Wandering Traders crossed the gravity anomaly unscathed.",
              "Los Comerciantes Errantes cruzaron la anomalía gravitacional ilesos."),
    _entry(9, "Estação abandonada PR-77 emite pulsos a cada 47 minutos.",
              "Abandoned station PR-77 pulses every 47 minutes.",
              "La estación abandonada PR-77 emite pulsos cada 47 minutos."),
    _entry(10, "Rumores de uma 'Frota Fantasma' não voltam a aparecer há séculos.",
               "Rumors of a 'Ghost Fleet' haven't resurfaced in centuries.",
               "Rumores de una 'Flota Fantasma' no reaparecen hace siglos."),
    _entry(11, "Naufrago humano resgatado — não falava nenhuma língua conhecida.",
               "Human castaway rescued — spoke no known language.",
               "Náufrago humano rescatado — no hablaba ninguna lengua conocida."),
    _entry(12, "Mineradoras do Cinturão Sul agora reportam diretamente a Pyxis.",
               "South-Belt miners now report directly to Pyxis.",
               "Los mineros del Cinturón Sur reportan ahora directamente a Pyxis."),
    _entry(13, "Tempestade solar derrubou três relês de comunicação.",
               "Solar storm took down three comm relays.",
               "La tormenta solar derribó tres repetidores de comunicación."),
    _entry(14, "Encontrei artefato octogonal — não corresponde a nenhuma civilização.",
               "Found an octagonal artifact — matches no known civilization.",
               "Encontré un artefacto octogonal — no concuerda con ninguna civilización."),
    _entry(15, "Avistei um aracnoide tamanho-cidade no horizonte de Helios-VI.",
               "Sighted a city-sized arachnoid on Helios-VI's horizon.",
               "Avisté un aracnoide del tamaño de una ciudad en Helios-VI."),
    _entry(16, "Sistema Veridian-3 mostra anomalia magnética constante.",
               "Veridian-3 shows a constant magnetic anomaly.",
               "Veridian-3 muestra una anomalía magnética constante."),
    _entry(17, "Estação Pyxis Central anunciou plano de cinco anos.",
               "Pyxis Central announced a five-year plan.",
               "Pyxis Central anunció un plan quinquenal."),
    _entry(18, "Federação proibiu cristais radioativos sem licença.",
               "Federation banned unlicensed radioactive crystals.",
               "La Federación prohibió cristales radiactivos sin licencia."),
    _entry(19, "Hoje é o aniversário do desaparecimento da Cruzadora Stellaris.",
               "Today marks the anniversary of the Stellaris Cruiser disappearance.",
               "Hoy es el aniversario de la desaparición del Crucero Stellaris."),
    _entry(20, "Mercado de Pyxis fechou em alta — cristais subiram 12%.",
               "Pyxis market closed up — crystals rose 12%.",
               "El mercado de Pyxis cerró al alza — cristales subieron 12%."),
    _entry(21, "Snipers piratas adotaram rifles de fusão termonuclear.",
               "Pirate snipers adopted thermonuclear fusion rifles.",
               "Los francotiradores piratas adoptaron rifles de fusión termonuclear."),
    _entry(22, "Dreadnaught avistado entrando em órbita de Helios-Prime.",
               "Dreadnaught sighted entering Helios-Prime orbit.",
               "Dreadnaught avistado entrando en órbita de Helios-Prime."),
    _entry(23, "A Anciã Iolanda diz: 'O espaço lembra de quem o atravessa.'",
               "Elder Iolanda says: 'Space remembers those who cross it.'",
               "La Anciana Iolanda dice: 'El espacio recuerda a quienes lo cruzan.'"),
    _entry(24, "Comerciante Tahir cobrou caro pela rota até Cervantes-IV.",
               "Trader Tahir charged dearly for the route to Cervantes-IV.",
               "El comerciante Tahir cobró caro por la ruta a Cervantes-IV."),
    _entry(25, "Capitã Lyra ofereceu contrato — escolta até o setor azul.",
               "Captain Lyra offered a contract — escort to the blue sector.",
               "La capitana Lyra ofreció contrato — escolta al sector azul."),
    _entry(26, "Engenheiro Praxis vendeu o plano da plataforma de mineração.",
               "Engineer Praxis sold the mining-platform blueprint.",
               "El ingeniero Praxis vendió el plano de la plataforma de minería."),
    _entry(27, "Hoje vi uma aurora sobre o cinturão de gelo — bom presságio.",
               "Saw an aurora over the ice belt today — good omen.",
               "Hoy vi una aurora sobre el cinturón de hielo — buen presagio."),
    _entry(28, "Sentinelas Atlas estão ativos em três sistemas.",
               "Atlas Sentinels are active in three systems.",
               "Los Centinelas Atlas están activos en tres sistemas."),
    _entry(29, "Crianças nascidas em Pyxis nunca pisaram em planeta.",
               "Children born on Pyxis have never set foot on a planet.",
               "Los nacidos en Pyxis nunca han pisado un planeta."),
    _entry(30, "Combustível subiu 8% no mercado negro de Cervantes.",
               "Fuel rose 8% on Cervantes' black market.",
               "El combustible subió 8% en el mercado negro de Cervantes."),
    _entry(31, "Federação oferece anistia para piratas que entregarem armas.",
               "Federation offers amnesty to pirates who turn in weapons.",
               "La Federación ofrece amnistía a los piratas que entreguen armas."),
    _entry(32, "Tarefa: localizar farol perdido de Helios-IX.",
               "Task: locate the lost Helios-IX beacon.",
               "Tarea: localizar el faro perdido de Helios-IX."),
    _entry(33, "Estação Mu-12 está sob bloqueio sanitário.",
               "Station Mu-12 is under sanitary lockdown.",
               "La estación Mu-12 está bajo bloqueo sanitario."),
    _entry(34, "Astrônomos de Pyxis preveem cometa para 2143-T.",
               "Pyxis astronomers predict a comet for 2143-T.",
               "Astrónomos de Pyxis predicen un cometa para 2143-T."),
    _entry(35, "Drones rebeldes invadiram a fronteira ocidental.",
               "Rebel drones breached the western frontier.",
               "Drones rebeldes invadieron la frontera occidental."),
    _entry(36, "Receita de filtro de oxigênio melhorado disponível em Pyxis.",
               "Improved oxygen filter recipe available on Pyxis.",
               "Receta de filtro de oxígeno mejorado disponible en Pyxis."),
    _entry(37, "Capitão Boreas relatou contato com nave-mãe alienígena.",
               "Captain Boreas reported contact with an alien mothership.",
               "El capitán Boreas reportó contacto con nave nodriza alienígena."),
    _entry(38, "Aniversário de 100 anos da Federação — celebrações em Helios-Prime.",
               "Federation's 100-year anniversary — celebrations on Helios-Prime.",
               "Aniversario 100 años de la Federación — festejos en Helios-Prime."),
    _entry(39, "Pesquisas em cristais radioativos prometem motor de dobra.",
               "Radioactive crystal research promises warp drive.",
               "Investigación en cristales radiactivos promete motor de curvatura."),
    _entry(40, "Cervantes-IV é o lar das filosofias 'sem-órbita'.",
               "Cervantes-IV is home to the 'orbit-less' philosophies.",
               "Cervantes-IV alberga las filosofías 'sin órbita'."),
    _entry(41, "Hoje encontrei um campo de ovos cristalinos — não toquei.",
               "Found a crystalline egg field today — did not touch.",
               "Hoy encontré un campo de huevos cristalinos — no toqué."),
    _entry(42, "Federação fechou rota Tau-9 — piratas reorganizaram.",
               "Federation closed Tau-9 route — pirates regrouped.",
               "La Federación cerró la ruta Tau-9 — los piratas se reagruparon."),
    _entry(43, "Mineradora coletiva descobriu jazida de cristal negro em Vesper.",
               "Mining collective found a black crystal vein on Vesper.",
               "La cooperativa minera encontró una veta de cristal negro en Vesper."),
    _entry(44, "Sentinelas Atlas exigem licença para entrar em sua nebulosa.",
               "Atlas Sentinels require a permit to enter their nebula.",
               "Los Centinelas Atlas exigen permiso para entrar en su nebulosa."),
    _entry(45, "Comerciantes propõem união Pyxis-Cervantes — em discussão.",
               "Traders propose a Pyxis-Cervantes union — under discussion.",
               "Los comerciantes proponen unión Pyxis-Cervantes — en discusión."),
    _entry(46, "Federação caça o dreadnaught 'Korvath' há doze anos.",
               "Federation has been hunting the dreadnaught 'Korvath' for twelve years.",
               "La Federación caza al dreadnaught 'Korvath' desde hace doce años."),
    _entry(47, "Sou o último da minha tripulação. Mantenho o log por hábito.",
               "I am the last of my crew. I keep the log out of habit.",
               "Soy el último de mi tripulación. Mantengo el log por costumbre."),
    _entry(48, "Helios-Prime sediará a próxima rodada de paz Federação–Piratas.",
               "Helios-Prime will host the next Federation–Pirate peace talks.",
               "Helios-Prime acogerá la próxima ronda de paz Federación-Piratas."),
    _entry(49, "Andróides industriais ganharam direito civil em Cervantes.",
               "Industrial androids gained civic rights on Cervantes.",
               "Los androides industriales obtuvieron derechos civiles en Cervantes."),
    _entry(50, "O céu sobre Helios-IX teve um eclipse triplo. Ninguém soube explicar.",
               "Helios-IX had a triple eclipse. No one could explain it.",
               "El cielo de Helios-IX tuvo un eclipse triple. Nadie supo explicarlo."),
    _entry(51, "Pyxis lançou primeira biblioteca pública orbital.",
               "Pyxis launched the first orbital public library.",
               "Pyxis lanzó la primera biblioteca pública orbital."),
    _entry(52, "Encontrei aracnoide pacífico — comeu cristais e se foi.",
               "Met a peaceful arachnoid — ate crystals and left.",
               "Encontré un aracnoide pacífico — comió cristales y se fue."),
    _entry(53, "Mercado fechou em baixa — escassez de ferro causa pânico.",
               "Market closed low — iron scarcity causes panic.",
               "El mercado cerró a la baja — la escasez de hierro causa pánico."),
    _entry(54, "Hoje minha nave passou de 1.000 horas-voo. Comemorei sozinho.",
               "My ship hit 1,000 flight hours today. I celebrated alone.",
               "Hoy mi nave superó las 1.000 horas de vuelo. Lo celebré solo."),
    _entry(55, "Lenda diz que Veridian-3 esconde portal interdimensional.",
               "Legend says Veridian-3 hides an interdimensional gateway.",
               "Cuenta la leyenda que Veridian-3 oculta un portal interdimensional."),
]


def get_entry(category, entry_id):
    lang = get_language()
    data = CODEX_DATA.get(category, {}).get(entry_id)
    if not data:
        return None
    name, desc = data.get(lang, data.get('pt', ('?', '?')))
    return {'name': name, 'description': desc}


def all_entries(category):
    return [(eid, get_entry(category, eid)) for eid in CODEX_DATA.get(category, {})]


def random_lore_entry():
    import random
    e = random.choice(LORE_LOG_ENTRIES)
    return e.get(get_language(), e.get('pt'))
